### ISSUE TITLE
Outdated latest release

### ISSUE THREAD

**Issue by jannismoeller** [LAtimes2/ols#3]
The link in the [README](https://github.com/LAtimes2/TeensyLogicAnalyzer#new-updated-ols-gui-is-available-for-windows-and-linux) of your _TeensyLogicAnalyzer_ repository points to the latest release of this repository. Unfortunately GitHub didn't recognize release ["Version 4.2"](https://github.com/LAtimes2/ols/releases/tag/v0.9.8-T4.2) as a full release and instead still links to ["Teensy 4 beta2"](https://github.com/LAtimes2/ols/releases/tag/v0.9.8-T4.2).
Could you change that, so that the link is pointing to the actually newest release?
It took me a while to figure out that the old firmware, that came with it, was the issue and not my Teensy4.1 board malfunctioning.

**Comment by LAtimes2** [comment]
Sorry about that. I don't know why the newer release wasn't listed as the latest, but I changed the beta release to a Pre-Release and now 4.2 is listed as the latest.

**Comment by jannismoeller** [comment]
Thanks for the quick response. Now everything's working as expected :)
